/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpctest.h"


void
sim_prog_1( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	operands  add_1_arg;
	int  *result_2;
	operands  sub_1_arg;

	#ifndef DEBUG
	clnt = clnt_create(host, SIM_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	#endif /* DEBUG */
	
	{ int a, b;
	printf("Enter two integers a, b ->  ");
	scanf("%d %d", &a, &b);
	add_1_arg.x = sub_1_arg.x = a;
	add_1_arg.y = sub_1_arg.y = b;
	}
	
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("sum = %d\n", *result_1);
	
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("dif = %d\n", *result_2);

	#ifndef DEBUG
	clnt_destroy( clnt );
	#endif /* DEBUG */
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	sim_prog_1( host );
}
