/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpctest.h"
int *
add_1_svc(operands *argp, struct svc_req *rqstp)
{

	static int  result;

	printf("server running ADD\n ");
	result = argp->x + argp->y;
	return(&result);
}

int *
sub_1_svc(operands *argp, struct svc_req *rqstp)
{

	static int  result;

	printf("server running SUB\n");
	result = argp->x - argp->y;
	return(&result);
}
